version: '3.1'

services:
  birdie:
    image: shamanis88/birdie:latest
    container_name: birdie
    restart: always
    environment:
      LOG_LEVEL: info
      LISTEN_NETWORK: tcp
      LISTEN_ADDR: 0.0.0.0:50051
    ports:
      - "50051:50051"
